### ISSUE TITLE
Updating outdated MongoDB in the example yml file of the documentation

### ISSUE THREAD

**Issue by DMW007** [isw-kudos/kudos-docs#11]
Hi Huddo-Team,
the provided `mongo.yml` file](https://docs.huddo.com/assets/config/kubernetes/mongo.yaml) linked on the [MongoDB documentation](https://docs.huddo.com/boards/kubernetes/mongo/) refers to MongoDB 4.10 release 1: `image: bitnami/mongodb:4.0.10-r1`

[It was released in 2019](https://docs.mongodb.com/manual/release-notes/4.0/#4.0.10---may-31--2019). Are there any reasons why this is not updated since more than two years? The following releases contains a lot of bugfixes. MongoDB 4.2/4.4 were avaliable, but if boards is not compatible, you currently can keep 4.0.x since it's still supported. As I understood the docs, patchlevels should not contain backward-incompatible changes. Only [minor releases like 4.2](https://docs.mongodb.com/manual/release-notes/4.2-compatibility/) removes deprecated features.

The example yml with the image tag seems to be [located here](https://github.com/isw-kudos/kudos-docs/blob/master/docs/assets/config/kubernetes/mongo.yaml).

**Comment by andylwelch** [comment]
Thanks for the feedback, this has been on our todo list, I have just updated it to use v4.4 as default now.

**Comment by DMW007** [comment]
Sounds good, thank you for updating! :+1: 
But the [`mongo.yml` in the repo](https://github.com/isw-kudos/kudos-docs/blob/master/docs/assets/config/kubernetes/mongo.yaml) is [still refering to 4.0.10](https://github.com/isw-kudos/kudos-docs/blob/master/docs/assets/config/kubernetes/mongo.yaml#L57) - is this file not fetched from this documentation git repo, as the rest of the documentation?

**Comment by andylwelch** [comment]
Sorry, just realised this issue was created on the old docs repository which is deprecated. Please see https://github.com/isw-kudos/huddo-docs/ for the latest documentation and updates which includes the update I did for this.
